# Site settings
title: Export Layers
description: "GIMP plug-in that exports layers as separate images"
baseurl: "/gimp-plugin-export-layers"
url: "https://khalim19.github.io"
repository: "khalim19/gimp-plugin-export-layers"
github_username: "khalim19"
email: "khalim19@gmail.com"
copyright_years: "2013-2019"

plugin_name: "export_layers"
plugin_version: "3.3"
latest_plugin_version_release_date: "January 18, 2019"
download_windows_suffix: "-windows.exe"
download_zip_suffix: ".zip"
sections_url: "/sections/"
license_remote_url: "blob/master/LICENSE"
license_local_filename: "LICENSE.txt"

plugins:
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-seo-tag

# Build settings
markdown: kramdown
is_release_build: false
